x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.36.0-alpine
    container_name: vaultwarden
    user: "${HOST_UID}:${HOST_GID}"
    restart: always
    logging: *default-logging
    stop_grace_period: 180s
    
    environment:
      - DOMAIN=${DOMAIN}:${HTTPS_PORT}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - ENABLE_DB_WAL=true
      - IP_HEADER=X-Forwarded-For
      - ORG_CREATION_USERS=all
      - ROCKET_PORT=${ROCKET_PORT}
      - TZ=Asia/Kolkata
      - ICON_CACHE_FOLDER=/data-t/icon_cache
      - TEMPLATES_FOLDER=/data-t/templates
      - TMP_FOLDER=/data-t/tmp
    
    volumes:
      - ./vw-data:/data:Z
      - ./vw-file/icon_cache:/data-t/icon_cache:Z
      - ./vw-file/templates:/data-t/templates:Z
      - ./vw-file/tmp:/data-t/tmp:Z
       
    networks:
      - vault_network
    deploy:
      resources:
        limits:
          memory: 512M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${ROCKET_PORT}/alive"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 2s


  
  caddy:
    image: ghcr.io/sidhartha426/caddy:2.11.4-porkbun-alpine
    container_name: caddy
    restart: always
    logging: *default-logging
    stop_grace_period: 60s
    
    ports:
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_API_SECRET_KEY=${PORKBUN_API_SECRET_KEY}
      - HTTPS_PORT=${HTTPS_PORT}
      - APP_UPSTREAM=vaultwarden:${ROCKET_PORT}
      - TZ=Asia/Kolkata
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vault_network
    deploy:
      resources:
        limits:
          memory: 256M
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    depends_on:
      vaultwarden:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:

networks:
  vault_network:
    name: vault_network
    driver: bridge
